/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "MONGODB_URI": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "arkytechno-launchpad-api": {
      "type": "sst.aws.ApiGatewayV1"
      "url": string
    }
    "user-manage-service-user-handler": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}